algoritmo "Sequências Básicas"
// Função : Ler informações e organiza-las
// Autor :  Eric Lucas
// Data : 20/12/2021
// Seção de Declarações 
var
     s:real
     n:caractere
inicio
      escreva("Digite o nome do funcionário(a): ")
      leia(n)
      escreva("Digite o salário mensal: R$")
      leia(s)
      Escreva(n," Tem o salário de R$",s," no mês atual")
// Seção de Comandos 
fimalgoritmo
