algoritmo "Sequências Básicas"
// Função : Soma Simples
// Autor :  Eric Lucas
// Data : 20/12/2021
// Seção de Declarações 
var
     n1,n2:inteiro
inicio
      escreval("=-=-=-=-=-=-=-=-=-=-=-=-=")
      escreval("      Soma Simples")
      escreval("=-=-=-=-=-=-=-=-=-=-=-=-=")
      Escreva("Digite o primeiro número: ")
      leia(n1)
      Escreva("Digite o segundo número: ")
      leia(n2)
      escreva("A soma",n1," +",n2," é:",n1+n2)
// Seção de Comandos 
fimalgoritmo
