algoritmo "SEQUÊNCIAS BÁSICAS"
// Função : Aquela de média
// Autor :  Eric Lucas
// Data : 20/12/2021
// Seção de Declarações 
var
     n1,n2,m:real
inicio
      escreval("=-=-=-=-=-=-=-=-=-=-=")
      escreval("   Aquela de média")
      escreval("=-=-=-=-=-=-=-=-=-=-=")
      escreva("Digite a primeira nota: ")
      leia(n1)
      escreva("Digite a segunda nota: ")
      leia(n2)
      m <- (n1+n2)/2
      escreva("A média final é:",m)
// Seção de Comandos 
fimalgoritmo
