algoritmo "SEQUÊNCIAS BÁSICAS"
// Função : Antecessor e Sucessor
// Autor :  Eric Lucas
// Data : 20/12/2021
// Seção de Declarações 
var
      n:inteiro
inicio
      escreval("-=-=-=-=-=-=-=-=-=-=-")
      escreval("     Ante e Suce")
      escreval("-=-=-=-=-=-=-=-=-=-=-")
      Escreva("Digite um número: ")
      leia(n)
      escreva("O antecessor de",n," é",n-1," o sucessor é",n+1)
// Seção de Comandos 
fimalgoritmo
