algoritmo "SEQUÊNCIAS BÁSICAS"
// Função :  A terça parte
// Autor :   Eric Lucas
// Data : 21/12/2021
// Seção de Declarações 
var
    n:real
    
inicio
      escreval("-=-=-=-=-=-=-=-=-=-=-")
      escreval("    Terça parte")
      escreval("-=-=-=-=-=-=-=-=-=-=-")
      escreva("Digite um número: ")
      leia(n)
      escreva("O dobro de",n," é:",n*2," a sua terça parte é:",n/3)
// Seção de Comandos 
fimalgoritmo
